var database_en = [
	{id:"AuX7nPBqDts", title: "Basic addition", local: true},
	{id:"aNqG4ChKShI", title: "Basic subtraction"},
	{id:"b22tMEc6Kko", title: "Example: Adding two digit numbers (no carrying)"},
	{id:"incKJchBCLo", title: "Subtraction 2"},
	{id:"sAw71J2kYJE", title: "Example: 2-digit subtraction (no borrowing)"},
	{id:"27Kp7HJYj2c", title: "Level 2 addition"},
	{id:"Wm0zq-NqEFs", title: "Carrying when adding three digit numbers"},
	{id:"O9zSHs1TWMM", title: "Why carrying works"},
	{id:"9hM32lsQ4aI", title: "Examples of carrying when adding three digit numbers"},
	{id:"fOXo4p4WDKM", title: "Addition 4"},
	{id:"9T3AAn-Cw3g", title: "Basic regrouping or borrowing when subtracting three digit numbers"},
	{id:"QOtam19NQcQ", title: "Regrouping when subtracting three digit numbers"},
	{id:"LSaaKau63Gg", title: "Regrouping twice when subtracting three digit numbers"},
	{id:"3lHBgFvr3yE", title: "Regrouping from 0 when subtracting three digit numbers"},
	{id:"RRk5qLd__Ro", title: "Borrowing once example 1"},
	{id:"8_fT1BsTmt4", title: "Borrowing once example 2"},
	{id:"OJ-wajo6oa4", title: "Regrouping (borrowing) twice example"},
	{id:"GBtcGO44e-A", title: "Alternate mental subtraction method"},
	{id:"QY8vv7eVVJE", title: "Subtraction word problem"},
	{id:"RNxwasijbAo", title: "Intro to multiplication"},
	{id:"cDpBtkU2cf8", title: "Multiplication as groups of objects"},
	{id:"vfMx9-rJXuo", title: "More on the concept of multiplication"},
	{id:"QI6x0KNxiCs", title: "The idea of division"},
	{id:"ez1MIB8_2O0", title: "Number line 1"},
	{id:"mvOkMYCygps", title: "Basic multiplication"},
	{id:"xO_1bYgoQvA", title: "Multiplication 2: The multiplication tables"},
	{id:"Yw3EoxC_GXU", title: "Example: Ways to represent multiplication"},
	{id:"qihoczo1Ujk", title: "Multiplication 3: 10,11,12 times tables"},
	{id:"MTzTqvzWzm8", title: "Division 1"},
	{id:"4I9iibPLdBw", title: "Example: Expressing division in multiple ways"},
	{id:"OCwLwaAQlMA", title: "Comparing with multiplication exercise"},
	{id:"bS6EmYzpou4", title: "Comparing ages"},
	{id:"fZtUn_THXnk", title: "Multiplication word problem example 1"},
	{id:"Z3qRkxzmYnU", title: "Division word problem example 1"},
	{id:"9CZfG3r5JBE", title: "Comparing magic strength"},
	{id:"jb8mFpA1YI8", title: "Multiplying by multiples of 10"},
	{id:"k68CPfcehTE", title: "2 digit times 1 digit example (no carrying)"},
	{id:"4BtXvopHXI8", title: "3 digit times 1 digit example (no carrying)"},
	{id:"SfxULALs_u8", title: "2 digit times 1 digit example"},
	{id:"TqRReFvbpXA", title: "3 digit times 1 digit example"},
	{id:"twMdew4Zs8Q", title: "4 digit times 1 digit example"},
	{id:"t8m0NalQtEk", title: "2-digit times a 2-digit number"},
	{id:"0WUXQNjdRvM", title: "Example: 2-digit times 2-digit"},
	{id:"-h3Oqhl8fPg", title: "Multiple digit numbers"},
	{id:"tx2Niw7aJJ8", title: "Multiplication estimation example"},
	{id:"_k3aWF6_b4w", title: "Multiplication 7: Old video giving more examples"},
	{id:"8Ft5iHhauJ0", title: "Introduction to long division"},
	{id:"BIGX05Mp5nw", title: "Introduction to remainders"},
	{id:"MbpmP1esh-Q", title: "Long division with remainder example"},
	{id:"NcADzGz3bSI", title: "More long division without and with remainders"},
	{id:"xXIG8ouHcsc", title: "Dividing by a two digit number"},
	{id:"gHTH6PKfpMc", title: "Level 4 division"},
	{id:"gS6TfWUv97I", title: "Lattice multiplication"},
	{id:"S3z4XqC_YSc", title: "Why lattice multiplication works"},
	{id:"R486L0M5cWk", title: "Partial quotient method of division"},
	{id:"omFelSZvaJc", title: "Partial quotient method of division 2"},
	{id:"anlOhNHlqwg", title: "Multi step word problems with whole numbers exercise 1"},
	{id:"cTveNRjWQYo", title: "Multi step word problems with whole numbers exercise 2"},
	{id:"l7h8A6SX5kY", title: "Multi step word problems with whole numbers exercise 3"},
	{id:"p0jCw2sqZgs", title: "Understanding multiplication through area models"},
	{id:"vbGwcvXgDlg", title: "Area model for multiplication"},
	{id:"Df9h5t64NlQ", title: "Divisibility tests for 2, 3, 4, 5, 6, 9, 10"},
	{id:"2G_Jr_XpnY4", title: "Recognizing divisibility"},
	{id:"NehkLV77ITk", title: "The why of the 3 divisibility rule"},
	{id:"XAzFGx3Ruig", title: "The why of the 9 divisibility rule"},
	{id:"vcn2ruTOwFo", title: "Finding factors of a number"},
	{id:"5xe-6GPR_qQ", title: "Finding factors and multiples"},
	{id:"AHRh3EpJQH0", title: "Divisibility intuition"},
	{id:"mIStB5X4U8M", title: "Prime numbers"},
	{id:"3h4UK62Qrbo", title: "Recognizing prime numbers"},
	{id:"ZKKDTfHcsG0", title: "Prime factorization"},
	{id:"XWq8bplP-_E", title: "Prime factorization exercise"},
	{id:"uzvopM4PZLw", title: "The fundamental theorem of arithmetic"},
	{id:"zWcfVC-oCNw", title: "Common divisibility examples"},
	{id:"znmPfDfsir8", title: "Least common multiple exercise"},
	{id:"QUem_2dkB9I", title: "Least common multiple exercise 2"},
	{id:"D6yHKOYJiso", title: "Least common multiple (LCM)"},
	{id:"cH-jaMCzIRk", title: "Old least common multiple"},
	{id:"bLTfBvkrfsM", title: "Greatest common divisor factor exercise"},
	{id:"jFd-6EPfnec", title: "Greatest common divisor"},
	{id:"1Vb8t7Y-pI0", title: "LCM and GCF (greatest common factor) word problems"},
	{id:"Hlal9ME2Aig", title: "Negative numbers introduction"},
	{id:"khwsah_svW8", title: "Number line 3 exercise examples"},
	{id:"VW6UrPKPInA", title: "Ordering negative numbers"},
	{id:"AcpIO62x2oo", title: "Example: Adding negative numbers"},
	{id:"NrVvu7cM8_o", title: "Example: Adding integers with different signs"},
	{id:"NQSN00zL5gg", title: "Adding and subtracting negative number examples"},
	{id:"lBscLuttQq0", title: "Why subtracting a negative is equivalent to adding a positive"},
	{id:"Oo2vGhVkvDo", title: "Negative number word problems 1"},
	{id:"fFdOr8U4mnI", title: "Adding decimals of different signs word problem"},
	{id:"C38B33ZywWs", title: "Adding/subtracting negative numbers"},
	{id:"47wjId9k2Hs", title: "Multiplying positive and negative numbers"},
	{id:"rK4sXm_MPWo", title: "Why a negative times a negative is a positive"},
	{id:"pzQY-9Nmtws", title: "Why a negative times a negative makes intuitive sense"},
	{id:"bQ-KR3clFgs", title: "Dividing positive and negative numbers"},
	{id:"4ve7OaCnDLs", title: "Example: Multiplying numbers with different signs"},
	{id:"d8lP5tR2R3Q", title: "Multiplying and dividing negative numbers"},
	{id:"frBJEYvyd-8", title: "Absolute value and number lines"},
	{id:"NvGTCzAfvr0", title: "Absolute value 1"},
	{id:"r6hS_8nm1jM", title: "Absolute value of integers"},
	{id:"hKkBlcnU9pw", title: "Comparing absolute values"},
	{id:"Ig7RSc-93Bs", title: "Absolute value word problems exercise"},
	{id:"FogJFEEYuO0", title: "Constructing and interpreting absolute value"},
	{id:"x-Dqe5U1TXA", title: "Decimal place value"},
	{id:"AuD2TX-90Cc", title: "Decimal place value 2"},
	{id:"G7QiIkYfeME", title: "Writing out a decimal in words"},
	{id:"he4kcTujy30", title: "Expanding out a decimal by place value"},
	{id:"5DlzmolR8Cg", title: "Writing a decimal to represent a quantity"},
	{id:"lR_kUUPL8YY", title: "Comparing place values in decimals"},
	{id:"-oFlAhtear4", title: "Using money to understand decimal place value"},
	{id:"3szFVS5p_7A", title: "Regrouping with decimals"},
	{id:"fNzM0lQHZsk", title: "Regrouping with decimals example"},
	{id:"dNnItWLuHH4", title: "Regrouping decimals example 2"},
	{id:"LpLnmuAyNWg", title: "Decimals on a number line"},
	{id:"uC09taczvOo", title: "Points on a number line"},
	{id:"w23DzA68KPE", title: "Positive and negative decimals on a number line"},
	{id:"gAV9kwvoD6s", title: "Comparing decimals example 1"},
	{id:"HCC96awA-FM", title: "Comparing decimals example 2"},
	{id:"f8B2dBQn3_U", title: "Comparing decimals example 3"},
	{id:"FwMYoK1QKso", title: "Comparing decimals example 4"},
	{id:"oLh_sIESQnY", title: "Adding decimals example 1"},
	{id:"ErHFQUhZ94I", title: "Adding decimals example 2"},
	{id:"w616LEmrHVE", title: "Adding decimals example 3"},
	{id:"Eq4mVCd-yyo", title: "Subtracting decimals"},
	{id:"c4fUaD4g4mc", title: "Adding decimals word problem"},
	{id:"hy_bDS3aHO4", title: "Subtracting decimals word problem"},
	{id:"0mOH-qNGM7M", title: "Subtracting decimals (old)"},
	{id:"JEHejQphIYc", title: "Multiplying decimals"},
	{id:"W7dImsrVa0Y", title: "Multiplying decimals example 2"},
	{id:"m5z6pOsxF_8", title: "Multiple examples multiplying decimals"},
	{id:"xUDlKV8lJbM", title: "Dividing completely to get decimal answer"},
	{id:"7ZwSd9gtnwI", title: "Dividing completely to get decimal answer example 2"},
	{id:"Z_NHrwK6ALE", title: "Dividing a decimal by a whole number"},
	{id:"cfr-yZxTH8Y", title: "Dividing a whole number by a decimal"},
	{id:"Nqts8zW8RxM", title: "Dividing decimals"},
	{id:"S0uuK7SQcA8", title: "Dividing decimal"},
	{id:"NM8qTo361ic", title: "Converting fractions to decimals (ex1)"},
	{id:"sCVyvfOLI6U", title: "Converting fractions to decimals (ex2)"},
	{id:"Gn2pdkvdbGQ", title: "Converting fractions to decimals"},
	{id:"Y1V5mZaMfTk", title: "Converting fractions to decimals example"},
	{id:"NzIoHQfStoM", title: "Decimals and fractions"},
	{id:"DR2DYe7PI74", title: "Converting decimals to fractions 1 (ex 1)"},
	{id:"9P80OLC6wKY", title: "Converting decimals to fractions 1 (ex 2)"},
	{id:"OS1g4PDdNdM", title: "Converting decimals to fractions 1 (ex 3)"},
	{id:"EGr3KC55sfU", title: "Converting decimals to fractions 2 (ex 1)"},
	{id:"qbMe4f2yvKs", title: "Converting decimals to fractions 2 (ex 2)"},
	{id:"Lvr2YsxG10o", title: "Describing the meaning of percent"},
	{id:"MokI3Fi8jpc", title: "Describing the meaning of percent 2"},
	{id:"-gB1y-PMWfs", title: "Representing a number as a decimal, percent, and fraction"},
	{id:"5z568fLBQyQ", title: "Converting decimals to percents (ex 1)"},
	{id:"3_caioiRu5I", title: "Converting decimals to percents (ex 2)"},
	{id:"MkpbtCRwcCE", title: "Converting percents to decimals (ex 1)"},
	{id:"T4JKO0OGjpQ", title: "Converting percents to decimals (ex 2)"},
	{id:"FaDtge_vkbg", title: "Finding percentages example"},
	{id:"AjYil74WrVo", title: "Percent word problems"},
	{id:"-lUEWEEpmIo", title: "Taking a percentage example"},
	{id:"JaScdH47PYg", title: "Identifying percent amount and base"},
	{id:"Hkwfibux88s", title: "Representing a number as a decimal, percent, and fraction 2"},
	{id:"Llt-KkHugRQ", title: "Ordering numeric expressions"},
	{id:"X2jVap1YgwI", title: "Growing by a percentage"},
	{id:"TvSKeTFsaj4", title: "Solving percent problems"},
	{id:"N4kDzoQOngY", title: "Solving percent problems 2"},
	{id:"DAikW24_O0A", title: "Solving percent problems 3"},
	{id:"_MIn3zFkEcc", title: "Rounding decimals"},
	{id:"BkwI6Uu0vi4", title: "Estimation with decimals"},
	{id:"eCJ76hz7jPM", title: "Significant figures"},
	{id:"eMl2z3ezlrQ", title: "More on significant figures"},
	{id:"xHgPtFUbAeU", title: "Addition and subtraction with significant figures"},
	{id:"iorZdz4dsBU", title: "Multiplying and dividing with significant figures"},
	{id:"mV0RxDZG05A", title: "Multiplying a decimal by a power of 10"},
	{id:"W_VhVHRal6o", title: "Dividing a decimal by a power of 10"},
	{id:"HLGCq2h4ihY", title: "Dividing a decimal by a power of 10 (part 2)"},
	{id:"FSpSrZQzzVs", title: "Adding and subtracting a decimal percentage and fraction"},
	{id:"xEDnwEOOf7Y", title: "Adding fractions decimals and percentages"},
	{id:"9tmtDBpqq9s", title: "Adding and subtracting three fractions"},
	{id:"Q_CljEweGOE", title: "Introduction to fractions"},
	{id:"-a_w0_VAo6U", title: "Identifying fraction parts"},
	{id:"NRJFZaSw1Y0", title: "Recognizing fractions exercise"},
	{id:"3XOt1fjWKi8", title: "Numerator and denominator of a fraction"},
	{id:"fVsxYtXOIXg", title: "Plotting basic fractions on the number line"},
	{id:"u2hLYcmI5y4", title: "Fraction word problems 1 exercise"},
	{id:"Bt60JVZRVCI", title: "Visualizing equivalent fractions"},
	{id:"dCQbfaQZtaY", title: "Equivalent fraction word problem example"},
	{id:"i-sAB-Z2_bE", title: "Equivalent fraction word problem example 2"},
	{id:"2nZsIeaiJUo", title: "Equivalent fraction word problem example 3"},
	{id:"xeLeYS7GRvY", title: "Fractions cut and copy 1 exercise"},
	{id:"WPimvspI0_c", title: "Fractions in lowest terms"},
	{id:"U2ovEuEUxXQ", title: "Equivalent fractions"},
	{id:"0JW9P_T4P_Y", title: "Equivalent fractions example"},
	{id:"lxjmR4pYIVU", title: "Finding common denominators"},
	{id:"8OKTrN0uT-Q", title: "Comparing fractions with greater than and less than symbols"},
	{id:"wbAxarp_Ug4", title: "Comparing fractions with like numerators and denominators"},
	{id:"Io9i1JkKgN4", title: "Comparing fractions"},
	{id:"2dbasvm3iG0", title: "Comparing fractions 2"},
	{id:"N8dIOmk_lHs", title: "Ordering fractions"},
	{id:"_E9fG8BYcBo", title: "Decomposing a fraction visually"},
	{id:"erZe85NrsK0", title: "Decomposing a mixed number"},
	{id:"l_Qj6aC6RV8", title: "Adding up to a fraction drag and drop example"},
	{id:"EJjnEau6aeI", title: "Adding fractions with like denominators"},
	{id:"UbUdyE1_b9g", title: "Subtracting  fractions"},
	{id:"52ZlXsFJULI", title: "Adding and subtracting fractions"},
	{id:"OVMceVL_CEQ", title: "Adding fractions with unlike denominators"},
	{id:"TuId1spuyoc", title: "Adding fractions (ex 1)"},
	{id:"N21Wh4Jqftc", title: "Subtracting fractions with unlike denominators"},
	{id:"QS1LMomm0Gk", title: "Adding fractions with different signs"},
	{id:"BKEtsv9MbyY", title: "Adding fractions examples"}
];

var database_fr = [
	{id:"7CKiA8d_x2U", title: " Les bases de l'addition ", local: true},
	{id:"Val2O1rLC44", title: " Les bases de la soustraction "},
	{id:"inm7J2V_CF0", title: " Exemple d'addition sans retenue "},
	{id:"gDnTQ2VROoI", title: "Comprendre la soustraction"},
	{id:"qhTqJbaeJ9Q", title: "Exemple de soustraction sans retenue"},
	{id:"BcVYZ3OsShU", title: "Addition : Introduction à la retenue"},
	{id:"BykCNzqHGDU", title: "Additions de nombres à 4 chiffres"},
	{id:"p4Rqs_vWu-M", title: "Soustraction avec retenue - Exemple 1"},
	{id:"F4jwP0VQe6Q", title: "Soustraction avec retenue - Exemple 2"},
	{id:"j_gfuaJluuY", title: "Soustraction avec retenue - Exemple 3"},
	{id:"V8sPoUAt1NI", title: " Méthode alternative pour la soustraction de tête "},
	{id:"XmkhQY3gpM8", title: "La droite numérique graduée"},
	{id:"MPv-3QxFBhk", title: "Les bases de la multiplication"},
	{id:"hIw-cwvybVM", title: "Tables de multiplication"},
	{id:"KsGYn1D0nr0", title: "Différentes façons d'écrire la multiplication"},
	{id:"n4HNA9b6Y4I", title: " Tables de multiplication de 10, de 11 et de 12 "},
	{id:"N-NmGG-t0eg", title: "Les bases de la division"},
	{id:"_ZSdGlAi4Vg", title: "Différentes façons d'écrire la division"},
	{id:"tE_gNrYPTM4", title: "Comparing with multiplication exercise"},
	{id:"_DzQ2BqTeCc", title: "Comparing ages"},
	{id:"0VWQnAeVV4Y", title: " Résoudre un problème avec une multiplication"},
	{id:"tXIok9lwM5Y", title: " Résoudre un problème avec une division"},
	{id:"W1o7X92TrIw", title: "Comparing magic strength"},
	{id:"FYyxMjF0xxI", title: "Multiplier par des multiples de 10"},
	{id:"sET1q1GkiWw", title: "2 digit times 1 digit example (no carrying)"},
	{id:"55y2d9W5nBE", title: "3 digit times 1 digit example (no carrying)"},
	{id:"seRlSL7gxIk", title: "2 digit times 1 digit example"},
	{id:"2PshoNDRky8", title: "3 digit times 1 digit example"},
	{id:"AnOqOPAtTv8", title: "4 digit times 1 digit example"},
	{id:"wWhDEYe1edo", title: " Introduction à la multiplication par un nombre à 2 chiffres"},
	{id:"HuDitrCDNMk", title: " Multiplier deux nombres à 2 chiffres"},
	{id:"ocVq8HyBb9Q", title: "Multiple digit numbers"},
	{id:"WBRXuW0pqE4", title: " Estimer une multiplication - Exemple "},
	{id:"m1E-2AXLOyo", title: "Plus d'exemples de multiplications"},
	{id:"WPPQdH3EHxo", title: "Poser une division"},
	{id:"R_0Dc11spZg", title: "Introduction to remainders"},
	{id:"Z2jUvB33HOo", title: "Long division with remainder example"},
	{id:"1XtGAigSZx0", title: "More long division without and with remainders"},
	{id:"fIBrICSRj3s", title: "Dividing by a two digit number"},
	{id:"D2uxGIX8VTk", title: "Division de niveau 4"},
	{id:"isc-dOSDHvY", title: "Multiplication par jalousie"},
	{id:"dl9dI181WN4", title: "Pourquoi la multiplication par jalousie fonctionne"},
	{id:"A2fSaO0lRLc", title: "Introduction à la méthode du quotient décomposé"},
	{id:"oTyxrdOkpho", title: "Méthode du quotient décomposé - Exemple"},
	{id:"KsDeopCk500", title: "Multi step word problems with whole numbers exercise 1"},
	{id:"MoXEi-3DmRI", title: "Multi step word problems with whole numbers exercise 2"},
	{id:"N0uMaP11Jdg", title: "Multi step word problems with whole numbers exercise 3"},
	{id:"-Ek3-InKoIM", title: "Understanding multiplication through area models"},
	{id:"MrxCaKK8a4Y", title: "Area model for multiplication"},
	{id:"t6GONPqFeck", title: "Caractères de divisibilité pour 2, 3, 4, 5, 6, 9 et 10"},
	{id:"J21SQx0DIqU", title: "Utiliser les caractères de divisibilité"},
	{id:"3uT-D0Lx7yY", title: "Le pourquoi de la règle de divisibilité par 3"},
	{id:"3MEa_vUMKAY", title: "Le pourquoi de la règle de divisibilité par 9"},
	{id:"hbSA5BehCV0", title: "Trouver les diviseurs d'un nombre"},
	{id:"T-o4M0F3oTQ", title: "Nombres Premiers"},
	{id:"u4fR1ghrUv0", title: "Recognizing prime numbers"},
	{id:"Bizg33ttvQ8", title: "Décomposition d'un nombre en facteurs premiers"},
	{id:"b4aymT3Gjzg", title: "Exercice sur la décomposition d'un nombre en un produit de facteurs premiers"},
	{id:"eou_p-XV6lQ", title: "Trouver les diviseurs et les multiples d'un nombre"},
	{id:"4_UqlwdBQ9U", title: "Exemples de divisibilité commune à plusieurs nombres"},
	{id:"9tE_vPtIiPo", title: "Plus Petit Commun Multiple - Exercice 1"},
	{id:"WQko2cUp5dw", title: "Plus Petit Commun Multiple - Exercice 2"},
	{id:"68idShNQmmk", title: "Least common multiple (LCM)"},
	{id:"W89QzEokJWU", title: "Greatest common divisor factor exercise"},
	{id:"Z2c922jlm-8", title: "Plus Grand Commun Diviseur (PGCD)"},
	{id:"FzkJNL7NbVY", title: "LCM and GCF (greatest common factor) word problems"},
	{id:"zOdZVH9dz_w", title: "Introduction aux nombres négatifs"},
	{id:"qAI4SptgdBo", title: "Ordonner des nombres négatifs"},
	{id:"HxK_Qwp48wY", title: "Example: Adding negative numbers"},
	{id:"LgMlUJetDlU", title: "Example: Adding integers with different signs"},
	{id:"cks5jNFgagI", title: "Why subtracting a negative is equivalent to adding a positive"},
	{id:"I-HcuDdd-fI", title: "Negative number word problems 1"},
	{id:"yKhsCncTFh8", title: "Adding decimals of different signs word problem"},
	{id:"X-jNwUF4HVw", title: "Ajouter et soustraire des nombres négatifs"},
	{id:"keZYh4Mpyo0", title: "Multiplier des nombres positifs et négatifs"},
	{id:"6gyLI_iw59o", title: "Pourquoi le produit de nombres négatifs est positif "},
	{id:"DcwSngAcryI", title: "Pourquoi il est logique que le produit de 2 nombres négatifs est positif"},
	{id:"NNkonrIbbfw", title: "Diviser des nombres négatifs et positifs"},
	{id:"xWr3exQ5dLg", title: "Example: Multiplying numbers with different signs"},
	{id:"5JhdkTzgTFU", title: "Multiplier et diviser des nombres négatifs"},
	{id:"03Sjb2eYZ-U", title: "Valeur absolue et droites numériques"},
	{id:"_RX_K_-guS0", title: "Absolute value 1"},
	{id:"vVdoi5Rxt90", title: "La valeur absolue de nombres entiers"},
	{id:"EKaehjN1PsU", title: "Comparer des valeurs absolues"},
	{id:"lpAP04JTCVo", title: "Absolute value word problems exercise"},
	{id:"DmXDr8Xtw44", title: " Interpréter les valeurs absolues "},
	{id:"73Dn3snraXc", title: "Valeur de position dans un nombre décimal"},
	{id:"oSjtTN1yAXY", title: "Decimal place value 2"},
	{id:"gEjweYRnmfQ", title: "Writing out a decimal in words"},
	{id:"U92Dqw66RZo", title: "Expanding out a decimal by place value"},
	{id:"CskV4-0u0PA", title: "Writing a decimal to represent a quantity"},
	{id:"hfxfn-DCJQc", title: "Comparing place values in decimals"},
	{id:"Ee72h0qBRpo", title: "Using money to understand decimal place value"},
	{id:"lnUQT8bFlMU", title: "Regroupements avec des nombres décimaux"},
	{id:"etJq7VkDOJo", title: "Regrouping with decimals example"},
	{id:"yFcjFF6J240", title: "Regroupements avec des nombres décimaux - Exemple 2"},
	{id:"QCv21Ef4Btc", title: "Nombres décimaux et droite numérique"},
	{id:"wcOPxljrnHI", title: "Points on a number line"},
	{id:"GZMmAJpNOJ0", title: "Positive and negative decimals on a number line"},
	{id:"Ow3xuRuw9d0", title: "Comparer des nombres décimaux - Exemple 1"},
	{id:"2OCJxUk2ae0", title: "Comparer des nombres décimaux - Exemple 2"},
	{id:"k-eg67FTOb8", title: "Comparing decimals example 3"},
	{id:"rmi_P5fw6BM", title: "Comparing decimals example 4"},
	{id:"YCXbmnUmRiQ", title: "Adding decimals example 1"},
	{id:"qiBU6izgquA", title: "Adding decimals example 2"},
	{id:"HuPVD3vScRQ", title: "Adding decimals example 3"},
	{id:"Xy684DdOpbM", title: "Soustraire des nombres décimaux - Niveau 2"},
	{id:"KozTckUxOGg", title: "Problème d'addition avec des nombres décimaux"},
	{id:"tGVscmC93nY", title: "Subtracting decimals word problem"},
	{id:"mvyanmyeBt8", title: "Soustraire des nombres décimaux - Exemple 3"},
	{id:"G1wuYQV9SdE", title: "Multiplier des nombres décimaux "},
	{id:"G0TP7_C1Ovg", title: "Multiplying decimals example 2"},
	{id:"CRl6AjzcJcQ", title: "Pousser la division après la virgule - Exemple 1"},
	{id:"pAFCwYOSWr0", title: "Pousser la division après la virgule - Exemple 2"},
	{id:"8MSEpcpn6t4", title: "Diviser un nombre décimal par un nombre entier"},
	{id:"EU6s3R3lIxg", title: "Diviser un nombre entier par un nombre décimal"},
	{id:"B575a_83-kc", title: "Diviser des nombres décimaux"},
	{id:"uDyGR3saBZ0", title: "Dividing decimal"},
	{id:"Y8vnIASywCo", title: "Converting fractions to decimals (ex1)"},
	{id:"4byWvYY3n5w", title: "Converting fractions to decimals (ex2)"},
	{id:"vpKE6QwZtfs", title: "Écrire une fraction sous forme décimale"},
	{id:"a9xeJd_444U", title: "Converting fractions to decimals example"},
	{id:"gdfMPligqM4", title: "Fractions et nombres décimaux"},
	{id:"3hWWWGIyLUw", title: "Converting decimals to fractions 1 (ex 1)"},
	{id:"MhbtkkH3SI8", title: "Converting decimals to fractions 1 (ex 2)"},
	{id:"ip4pBX5G7SU", title: "Converting decimals to fractions 1 (ex 3)"},
	{id:"EabwtEkIvi0", title: "Écrire un nombre décimal sous forme de fraction"},
	{id:"Zfre6pKuwcY", title: "Describing the meaning of percent"},
	{id:"W38COMyBKpk", title: "Describing the meaning of percent 2"},
	{id:"t6Aov9qOcxo", title: "Representing a number as a decimal, percent, and fraction"},
	{id:"YcdXkLtxeUo", title: "Converting decimals to percents (ex 1)"},
	{id:"qwc7p_DxQRo", title: "Converting decimals to percents (ex 2)"},
	{id:"yuyX0YJlKQw", title: "Converting percents to decimals (ex 1)"},
	{id:"R2GBcENN788", title: "Converting percents to decimals (ex 2)"},
	{id:"SgFaLduHeAE", title: "Finding percentages example"},
	{id:"wcwDRkM-mSQ", title: "Problèmes avec des pourcentages"},
	{id:"_n7mTBAedeA", title: "Taking a percentage example"},
	{id:"8dv5foyMgCM", title: "Pourcentage, valeur initiale et valeur finale"},
	{id:"Q92181IRCls", title: "Ecrire un nombre sous forme d'une fraction, d'un pourcentage, ou d'un nombre décimal"},
	{id:"rteWGslOMg8", title: "Ordonner des expressions numériques"},
	{id:"GAK9ukkdYL8", title: "Pourcentage d'augmentation"},
	{id:"XjRRX1-mtNs", title: "Résoudre un problème avec les pourcentages - Exemple 1"},
	{id:"5yEJnOhYkeM", title: "Solving percent problems 2"},
	{id:"PPnanSA35tw", title: "Solving percent problems 3"},
	{id:"LX9KyA1OlP8", title: "Arrondir un nombre décimal"},
	{id:"6Fr15yOl5Os", title: "Chiffres significatifs"},
	{id:"8HOOtaZM1NM", title: "Règles de détermination du nombre de chiffres significatifs"},
	{id:"219hOmxx9Es", title: "Chiffres significatifs du résultat d'une addition ou d'une soustraction"},
	{id:"1p4jXyhzdZo", title: "Chiffres significatifs du résultat d'une multiplication ou d'une division"},
	{id:"6TFRYPbOr2Y", title: "Multiplier des nombres décimaux par une puissance de 10"},
	{id:"CuWGZWWCcGA", title: "Diviser des nombres décimaux par une puissance de 10"},
	{id:"HlebDFXtuh4", title: "Dividing a decimal by a power of 10 (part 2)"},
	{id:"Xl7hpG-J6IY", title: "Adding and subtracting a decimal percentage and fraction"},
	{id:"3jai7sLBSl4", title: "Adding fractions decimals and percentages"},
	{id:"Wjy0uhT-UMs", title: "Adding and subtracting three fractions"},
	{id:"bk74f8QIG_0", title: "Introduction aux fractions"},
	{id:"DmNytpQ0nsM", title: "Reconnaître les fractions"},
	{id:"kTeV9yEXxXA", title: "Reconnaître des fractions - Exemple"},
	{id:"zshg1JfkChk", title: "Identifier le numérateur et le dénominateur"},
	{id:"DKNGyHEt4_o", title: "Placer des fractions sur la droite numérique"},
	{id:"8p-ZykFNKb0", title: "Fraction word problems 1 exercise"},
	{id:"c5aLKLaMULk", title: "Visualiser des fractions équivalentes"},
	{id:"xqTeEx8NZGc", title: "Problème sur les fractions équivalentes - Exemple 1"},
	{id:"EhWZwigQ_Uk", title: "Problème sur les fractions équivalentes - Exemple 2"},
	{id:"CJ_QegL6M9A", title: "Problème sur les fractions équivalentes - Exemple 3"},
	{id:"_1vo-qUswcg", title: "Fractions équivalentes - Niveau 1"},
	{id:"cdAIp-EBprk", title: "Equivalent fractions example"},
	{id:"1zGExtDguig", title: "Comparer des fractions"},
	{id:"4NHixVi6Wq4", title: "Comparing fractions 2"},
	{id:"c9-VfMi82ic", title: "Ordonner des fractions"},
	{id:"GsfDieCERpk", title: "Décomposer une fraction visuellement"},
	{id:"nyiZOJWKto0", title: "Additionner des fractions ayant le même dénominateur"},
	{id:"bPVup4ElwRw", title: "Subtracting  fractions"},
	{id:"GLjFc3WezSM", title: "Additionner et soustraire des fractions"},
	{id:"djAOyULj3iY", title: "Additionner des fractions ayant des dénominateurs différents"},
	{id:"1CqDpXgm4Gs", title: "Adding fractions (ex 1)"},
	{id:"YpR8xjzMISI", title: "Subtracting fractions with unlike denominators"},
	{id:"6ZBt5OUl_x0", title: "Additionner des fractions de signes différents"}
];

var database_es = [
	{id:"yHeTx8SAaOQ", title: "Sumas básicas", local: true},
	{id:"CIljE0sQRV8", title: "Restas básicas"},
	{id:"vrjBZsP1ENk", title: "Sumando números de dos dígitos (sin llevada). Ejemplo"},
	{id:"gyh_9uPdDEg", title: "Restas 2"},
	{id:"DHIQ2DEf_ho", title: "Restando números de dos dígitos (sin pedir prestado). Ejemplo"},
	{id:"qlP585OyE4Q", title: "Sumas nivel 2"},
	{id:"Zrjb5wPlqoU", title: "Carrying when adding three digit numbers"},
	{id:"cVSuEsR_xyI", title: "Why carrying works"},
	{id:"xjpvHCBdZOI", title: "Examples of carrying when adding three digit numbers"},
	{id:"cyBTtJYD6Ds", title: "Sumas 4"},
	{id:"xCEQRQeWHC4", title: "Basic regrouping or borrowing when subtracting three digit numbers"},
	{id:"j84hRaBH_Zs", title: "Regrouping when subtracting three digit numbers"},
	{id:"p341ietbG_4", title: "Regrouping twice when subtracting three digit numbers"},
	{id:"2WNv6kxjCWU", title: "Regrouping from 0 when subtracting three digit numbers"},
	{id:"EyEae0FCTYM", title: "Pidiendo prestado una vez. Ejemplo 1"},
	{id:"KWbJl7PD4Bg", title: "Pidiendo prestado una vez. Ejemplo 2"},
	{id:"3MzESVgtDuo", title: "Reagrupando (pedir prestado) dos veces. Ejemplo"},
	{id:"VluzHOAOSDs", title: "Cómo resto en mi cabeza"},
	{id:"G4Uz3EcXV5M", title: "Introducción a la multiplicación"},
	{id:"NAejUfwVooU", title: "La multiplicación vista como grupos de objetos"},
	{id:"w61xGdfhK3k", title: "Más sobre el concepto de multiplicación"},
	{id:"TBz0sJMpaTE", title: "La idea de la división"},
	{id:"xiX_5oZwhpc", title: "La recta numérica 1"},
	{id:"I0YEQeQ-UG4", title: "La multiplicación básica"},
	{id:"pzczgUH_Uog", title: "Multiplicación 2: las tablas de multiplicar"},
	{id:"rqtM7ZOeplY", title: "Formas de representar la multiplicación. Ejemplo"},
	{id:"o-jmkN5tamk", title: "Multiplicación 3: las tablas de multiplicar del 10,11 y 12"},
	{id:"_AHL8tJgqBA", title: "División 1"},
	{id:"nvuPVEYSz4A", title: "Expresando la división de varias maneras. Ejemplo"},
	{id:"qpFysiVp2oM", title: "Comparing with multiplication exercise"},
	{id:"dGklKavl58w", title: "Comparing ages"},
	{id:"QEaDOx4CuSQ", title: "Problema de multiplicación. Ejemplo 1"},
	{id:"0Iq6KScTe04", title: "Problema de división. Ejemplo 1"},
	{id:"Y53SZt7LWpc", title: "Comparing magic strength"},
	{id:"d9wKaybbDQ8", title: "Multiplicando por múltiplos de 10"},
	{id:"Vcjd1HdUDSQ", title: "2 digit times 1 digit example (no carrying)"},
	{id:"K6Qpx9vQL6g", title: "3 digit times 1 digit example (no carrying)"},
	{id:"yaJnfF3nIAY", title: "2 digit times 1 digit example"},
	{id:"9OmBNDZao48", title: "3 digit times 1 digit example"},
	{id:"UweuiXfsuc4", title: "4 digit times 1 digit example"},
	{id:"z8bdz9oGD0M", title: "2 dígitos por 2 dígitos"},
	{id:"iv--pXGJiV0", title: "2 dígitos por 2 dígitos. Ejemplo"},
	{id:"05gL_QHRk2Q", title: "Multiple digit numbers"},
	{id:"Ae4elpWwyH4", title: "Estimación de la multiplicación. Ejemplo"},
	{id:"Cbf-13qA2YQ", title: "Multiplicación 7: video viejo con más ejemplos"},
	{id:"zm0PLMg67vk", title: "Introducción a las divisiones largas"},
	{id:"D2D-htSpQZA", title: "Introduction to remainders"},
	{id:"26iuuTVemG4", title: "Long division with remainder example"},
	{id:"t130wzJWk_Q", title: "More long division without and with remainders"},
	{id:"VLeH5fxECfE", title: "Dividing by a two digit number"},
	{id:"jnJm0bIhBe8", title: "División nivel 4"},
	{id:"-Ia7BGChyb8", title: "La multiplicación reticular"},
	{id:"kB5v_vjR-mo", title: "Por qué funciona la multiplicación reticular"},
	{id:"KrBDDb-mKi8", title: "Método de división del cociente parcial"},
	{id:"59TXlNY1Fdc", title: "Método de división del cociente parcial 2"},
	{id:"D5JtpHjRVKI", title: "Multi step word problems with whole numbers exercise 1"},
	{id:"yvOfKBkCH3c", title: "Multi step word problems with whole numbers exercise 2"},
	{id:"aSNDcjX5EnY", title: "Multi step word problems with whole numbers exercise 3"},
	{id:"PLXRl0JKrMo", title: "Understanding multiplication through area models"},
	{id:"XLsbLcmL_YM", title: "Area model for multiplication"},
	{id:"IABvlU2Sw3E", title: "Pruebas de divisibilidad por 2, 3, 4, 5, 6, 9, 10"},
	{id:"b6LuiUyYZSI", title: "Reconociendo la divisibilidad"},
	{id:"rWpUrd8BRI4", title: "El porqué de la regla de divisibilidad entre 3"},
	{id:"CO3kYDqW4jo", title: "El porqué de la regla de divisibilidad entre 9"},
	{id:"rEsPblIXN9s", title: "Encontrando los factores de un número"},
	{id:"BOiuVmNoz70", title: "Encontrando factores y múltiplos"},
	{id:"BrGDvBBcDsM", title: "Ideas intuitivas sobre la divisibilidad"},
	{id:"aCuDnUUm2RQ", title: "Números primos"},
	{id:"dCY7MrHXST0", title: "Recognizing prime numbers"},
	{id:"M2KRXQHGIeo", title: "Factorización en primos"},
	{id:"2EudueoET_c", title: "Factorización en primos. Ejercicio"},
	{id:"o1QZRu08hiw", title: "El teorema fundamental de la aritmética"},
	{id:"GDgVe2BiRWM", title: "Divisores comunes. Ejemplos"},
	{id:"Z9MiA2MNw1o", title: "Mínimo común múltiplo. Ejercicio"},
	{id:"NuHvXy4uy7I", title: "Mínimo común múltiplo. Ejercicio 2"},
	{id:"rM7U6-SQ51U", title: "Least common multiple (LCM)"},
	{id:"g6a7sMRSzMk", title: "Greatest common divisor factor exercise"},
	{id:"N90qSkN5kX8", title: "Máximo común divisor"},
	{id:"SfTWCwOeHTU", title: "LCM and GCF (greatest common factor) word problems"},
	{id:"JpcE8VRjVN4", title: "Introducción a los números negativos"},
	{id:"8U8IEV9-0dI", title: "Number line 3 exercise examples"},
	{id:"P6ATIKyLrqo", title: "Ordenando números negativos"},
	{id:"_xYhaa59Izw", title: "Example: Adding negative numbers"},
	{id:"rawQzxMKUqs", title: "Example: Adding integers with different signs"},
	{id:"nNVtfZ1dNmI", title: "Adding and subtracting negative number examples"},
	{id:"UaV7RlsWzQk", title: "Why subtracting a negative is equivalent to adding a positive"},
	{id:"jEmHyXH4j9E", title: "Negative number word problems 1"},
	{id:"zICUqoH908Q", title: "Adding decimals of different signs word problem"},
	{id:"BIeUtgvM4qE", title: "Suma/resta de números negativos"},
	{id:"eCtIOTjxfx4", title: "Multiplicando números positivos y negativos"},
	{id:"lsEAxlYJsfo", title: "Por qué un negativo por un negativo es un positivo"},
	{id:"8fxtvSsWRWM", title: "Por qué tiene sentido intuitivamente multiplicar un negativo por otro"},
	{id:"AIA0dj66tNQ", title: "Dividiendo números positivos y negativos"},
	{id:"GUO1IQVvmzU", title: "Example: Multiplying numbers with different signs"},
	{id:"nlB5_Oxdad8", title: "Multiplicando y dividiendo números negativos"},
	{id:"37VwBrkWUAc", title: "Valor absoluto y rectas numéricas"},
	{id:"07OC5zPjdXk", title: "Absolute value 1"},
	{id:"8fS10RUVWIY", title: "Valor absoluto de números enteros"},
	{id:"ZsLvt3oKuAA", title: "Comparando valores absolutos"},
	{id:"4fxopE__0xk", title: "Absolute value word problems exercise"},
	{id:"5vqq2MBbi4o", title: "Construyendo e interpretando un valor absoluto"},
	{id:"T0zgal3EknE", title: "Valor posicional de los decimales"},
	{id:"w5-qh6YQOSw", title: "Decimal place value 2"},
	{id:"Jmk3fRGsBFM", title: "Writing out a decimal in words"},
	{id:"gZKk4WccvWY", title: "Expanding out a decimal by place value"},
	{id:"bLC-izbPuMw", title: "Writing a decimal to represent a quantity"},
	{id:"5wGOr1QB6RM", title: "Comparing place values in decimals"},
	{id:"YF-L8G1LM7o", title: "Using money to understand decimal place value"},
	{id:"XCzpzp7iqUQ", title: "Reagrupando con decimales"},
	{id:"vwUPgBJa478", title: "Regrouping with decimals example"},
	{id:"P09s3zWtbGo", title: "Reagrupando decimales. Ejemplo 2"},
	{id:"qWtoGZEjgaQ", title: "Decimales en la recta numérica"},
	{id:"t0o6w404mNg", title: "Points on a number line"},
	{id:"xnlSDwE8UdM", title: "Positive and negative decimals on a number line"},
	{id:"hvju3hP9Ugk", title: "Comparando decimales. Ejemplo 1"},
	{id:"RJlwHjvQSLI", title: "Comparando decimales. Ejemplo 2"},
	{id:"2K5u9wpzNG8", title: "Comparing decimals example 3"},
	{id:"nOxNuOYnmko", title: "Comparing decimals example 4"},
	{id:"apKxjnC78oE", title: "Adding decimals example 1"},
	{id:"pPGn3XOLpAc", title: "Adding decimals example 2"},
	{id:"6RMdChCsHV4", title: "Adding decimals example 3"},
	{id:"elchS7sGiZM", title: "Restando decimales"},
	{id:"xR-CJx2ls2U", title: "Problema de suma de decimales"},
	{id:"BLfzjUgGa30", title: "Subtracting decimals word problem"},
	{id:"nwUWghW6L_U", title: "Restando decimales (viejo)"},
	{id:"SXdgKrTyhKY", title: "Multiplicando decimales"},
	{id:"47x4dc1eYvs", title: "Multiplying decimals example 2"},
	{id:"6_1A7Xz99Z4", title: "Dividiendo completamente para obtener una respuesta decimal"},
	{id:"A7Uf3kQF6mQ", title: "Dividiendo completamente para obtener una respuesta decimal ejemplo 2"},
	{id:"Zb2twPijpVA", title: "Dividiendo un decimal entre un número entero"},
	{id:"RYTHnZmyzXs", title: "Dividiendo un número entero entre un decimal"},
	{id:"_1St8Sg_OWc", title: "Dividiendo decimales"},
	{id:"Iad0R0Yet_M", title: "Dividing decimal"},
	{id:"lO1Lw_kauaY", title: "Converting fractions to decimals (ex1)"},
	{id:"NfSz46a-TSw", title: "Converting fractions to decimals (ex2)"},
	{id:"UDZ469gKaD4", title: "Convirtiendo fracciones a decimales"},
	{id:"ed1sGY-pCZQ", title: "Converting fractions to decimals example"},
	{id:"cMghbkUrrLc", title: "Fracciones y decimales"},
	{id:"bEaCVSFS9dw", title: "Converting decimals to fractions 1 (ex 1)"},
	{id:"2GpIjBWiIkw", title: "Converting decimals to fractions 1 (ex 2)"},
	{id:"inPVHRH8Zh8", title: "Converting decimals to fractions 1 (ex 3)"},
	{id:"rn9BIx6WJ4w", title: "Convirtiendo decimales a fracciones 2. Ejemplo 1"},
	{id:"ANLZQrIxQUw", title: "Convirtiendo decimales a fracciones 2. Ejemplo 2"},
	{id:"9CwbwpXNx0M", title: "Describing the meaning of percent"},
	{id:"xkI_dhE-fus", title: "Describing the meaning of percent 2"},
	{id:"UJExBkvt_do", title: "Representing a number as a decimal, percent, and fraction"},
	{id:"rmE7w2lnHt8", title: "Converting decimals to percents (ex 1)"},
	{id:"YlCRlrrOA4A", title: "Converting decimals to percents (ex 2)"},
	{id:"zC-KHjxZs60", title: "Converting percents to decimals (ex 1)"},
	{id:"qDzk8iBe5IM", title: "Converting percents to decimals (ex 2)"},
	{id:"bH-CiO1VNI8", title: "Finding percentages example"},
	{id:"USD8eTa8af8", title: "Problemas de porcentajes"},
	{id:"tR2ea2nRBHQ", title: "Taking a percentage example"},
	{id:"Vci5SYOSQaE", title: "Identificando la base y el porcentaje"},
	{id:"WVmkeG-KfwM", title: "Representando un número como una fracción, un decimal y un porcentaje 2"},
	{id:"Af0ZhDo-f5A", title: "Ordenando expresiones numéricas"},
	{id:"saSvC27eO3g", title: "Acrecentando por un porcentaje"},
	{id:"_HxLDNtzY0Y", title: "Solución de problemas de porcentaje"},
	{id:"CEp6C21wZ_0", title: "Solving percent problems 2"},
	{id:"c5Dh8s_bDB8", title: "Solving percent problems 3"},
	{id:"r6KX5y7n57g", title: "Redondeando decimales"},
	{id:"oDOjAxX9x7o", title: "Cifras significativas"},
	{id:"OhuXpzOwiLs", title: "Más sobre las cifras significativas"},
	{id:"9NRq0UhRjEg", title: "Suma y resta con cifras significativas"},
	{id:"SVunyKKbx78", title: "Multiplicando y dividiendo con cifras significativas"},
	{id:"BK0bXjCWd2w", title: "Multiplicando un decimal por una potencia de 10"},
	{id:"hC5C5ujn7Lg", title: "Dividiendo un decimal entre una potencia de 10"},
	{id:"ghyXvWuxpJ4", title: "Dividing a decimal by a power of 10 (part 2)"},
	{id:"uskaBKKkdLs", title: "Adding and subtracting a decimal percentage and fraction"},
	{id:"BzlxTuAKKLU", title: "Adding fractions decimals and percentages"},
	{id:"dHDybJjXNyk", title: "Adding and subtracting three fractions"},
	{id:"uVGsyX2e-kk", title: "Introducción a las fracciones"},
	{id:"9MRXgf5kWDU", title: "Identificando las partes de una fracción"},
	{id:"rnzMoKtXmZk", title: "Reconociendo fracciones. Ejercicio"},
	{id:"BdYSaXECBAM", title: "El numerador y el denominador de una fracción"},
	{id:"KisDkl_9fqU", title: "Graficando fracciones básicas en la recta numérica"},
	{id:"2LFGJzxVO1k", title: "Fraction word problems 1 exercise"},
	{id:"xCdJ49Q_fVU", title: "Visualizando fracciones equivalentes"},
	{id:"ldmfjlXFnBw", title: "Problema de fracciones equivalentes. Ejemplo"},
	{id:"o0wH9Z7gpzo", title: "Problema de fracciones equivalentes. Ejemplo 2"},
	{id:"5fYDR0Dko_o", title: "Problema de fracciones equivalentes. Ejemplo 3"},
	{id:"8lwnoePrKmM", title: "Fracciones cortar y pegar 1. Ejercicio"},
	{id:"yNHsWgsEjt0", title: "Las fracciones en su mínima expresión"},
	{id:"CgoYtewRaa0", title: "Fracciones equivalentes"},
	{id:"-PPqKxgjF6o", title: "Equivalent fractions example"},
	{id:"P-rYCkXm5zw", title: "Encontrando los denominadores comunes"},
	{id:"FkGV1-O8Huw", title: "Comparando fracciones con los símbolos 'mayor que' y 'menor que'"},
	{id:"9jvJN8xmv1M", title: "Comparando fracciones que tienen numeradores o denominadores iguales"},
	{id:"5qyHfhLLkvs", title: "Comparando fracciones"},
	{id:"l6c8_VGMd0Y", title: "Comparing fractions 2"},
	{id:"-Pq_kOHVCC8", title: "Ordenando fracciones"},
	{id:"r8OXptGkEsU", title: "Descomposición visual  de fracciones"},
	{id:"BC0D9XAvLKQ", title: "Descomposición de números mixtos"},
	{id:"sfI4mvmtesM", title: "Adding up to a fraction drag and drop example"},
	{id:"iHo6WMqw3LI", title: "Sumando fracciones con el mismo denominador"},
	{id:"X5gX14IDf3E", title: "Subtracting  fractions"},
	{id:"Yx5IgvbUnK8", title: "Sumando y restando fracciones"},
	{id:"l0vi2OFj73c", title: "Sumando fracciones con denominadores diferentes"},
	{id:"cc8tqvtlfaM", title: "Adding fractions (ex 1)"},
	{id:"UaH8RhItcjk", title: "Subtracting fractions with unlike denominators"},
	{id:"pHHh9laVJZU", title: "Sumando fracciones con signos diferentes"}
];