FROM node:5.7.1-slim
RUN mkdir -p /opt
ADD https://yarnpkg.com/latest.tar.gz /opt/latest.tar.gz
WORKDIR /opt
RUN tar zxvf /opt/latest.tar.gz
RUN mv /opt/dist /opt/yarn
ENV PATH "$PATH:/opt/yarn/bin"

WORKDIR /sugarizer-repo/server
CMD yarn install; node /sugarizer-repo/server/sugarizer.js /sugarizer-repo/docker/sugarizer-docker.ini