//Copyright (c) 2013, Playful Invention Company.

//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:

//The above copyright notice and this permission notice shall be included in
//all copies or substantial portions of the Software.

//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//THE SOFTWARE.

// -----

// GridPaint has been kept extremely minimal as an explicit design choice.
// If you want to add features please make a fork with a different name.
// Thanks in advance


var gallery = [];
var galleryname = "journal";


var defaultGallery=
["wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"oyoyoyoyyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyyoyoyoyoyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyoyoyoyoyyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyyoyoyoyoyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyoyoyoyoyyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyyoyoyoyo",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"yyyyykkykkkkkyykyyyyykkykkkkkyykyyyyykkykkkkkyykkkkkkyykyyyyykkykkkkkyykyyyyykkykkkkkyykyyyyykkyyyyyykkykkkkkyykyyyyykkykkkkkyykyyyyykkykkkkkyykkkkkkyykyyyyykkykkkkkyykyyyyykkykkkkkyykyyyyykkyyyyyykkykkkkkyykyyyyykkykkkkkyykyyyyykkykkkkkyyk",
"bbbbbbbbbbbbbbbbbbbbbbbbyyybbbybbyyybbbybbbbbbbbbbbbbbnbbbbbbbbnbbbbbbbbyybybybbybyyybbbbbbbbbbbnnnnbnnnnnnnnbnnbbbbbbonbbbbbbnobbbbbbbnoooobboonnnnnnngnnnnnngnnnnnnnggnnnnnnngnnnnnnnnnnnnnngngggggggggggggggggggggggggggggggggggggggggggggggg",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"bbgggbrrggbbbgyybbgggbrrggbbbgyybbgggbrrggbbbgyyryyrrryyyrryyyrrryyrrryyyrryyyrrryyrrryyyrryyyrrggbbyygbbbggrrbgggbbyygbbbggrrbgggbbyygbbbggrrbgbbgggbrrggbbbgyybbgggbrrggbbbgyybbgggbrrggbbbgyyrvvrrrvvyooyyyoorvvrrrvvyvvyyyvvroorrrooyvvyyyvv",
"vvvvvvbvbbbbvbbbbbbbbbybbyybbbyybyybbbyybyybbbyybbbvvbybywyybyryywwyyywrwwwwwwwwwwwwwwowwwwwwywoyybbbywbwwrwwrrwwwwwrwrrwwwwwwowwwowwoowwowwowwowggybwggwggwwrrgwggwrwgrwggwwwggwogwwoggwgowowgggnngggnnnnnngnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnngnn",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"];


function loadGallery(loaded){
	if (loaded != null) {
		gallery = loaded.gallery.split('#');
		mode = loaded.mode;
		selected = loaded.selected;
	} else {
		gallery = defaultGallery;
		mode = 'selector';
		selected = 0;
	}
}

function saveGallery(){
	activity.getDatastoreObject();
	var datastoreObject = activity.getDatastoreObject();
	var data = { gallery: gallery.join('#'), mode: mode, selected: selected };
	var jsonData = JSON.stringify(data);
    datastoreObject.setDataAsText(jsonData);
    datastoreObject.save(function () {});	
}

